version: '3'

tasks:
  proto:
    desc: generate go files based on protobuf files
    cmds:
      - for: ["product", "user"]
        cmd: |
          mkdir -p ./internal/service/proto/{{ .ITEM }} && \
          protoc --go_out=./internal/service/proto/{{ .ITEM }} \
          --go_opt=paths=source_relative \
          --go-grpc_out=./internal/service/proto/{{ .ITEM }} \
          --go-grpc_opt=paths=source_relative \
          ./proto/{{ .ITEM }}.proto